# version: '3.8'
#services:
# db:
#  image: mysql:8
# environment:
#     MYSQL_DATABASE: MySQL AWS
#      MYSQL_ROOT_PASSWORD: admin123
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#  app:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#
#volumes:
#  db_data:
